export const fieldBindings = Object.freeze([
  { path: 'applicant.intent', selector: '#ch2 .pill-group', index: 0, type: 'choice' },
  { path: 'applicant.marriageTimeline', selector: '#ch2 .pill-group', index: 1, type: 'choice' },
  { path: 'applicant.availableWithinFourWeeks', selector: '#ch2 .pill-group', index: 2, type: 'choice' },
  { path: 'applicant.preferredAge.minimum', selector: '#ageRangeMinimum', type: 'number' },
  { path: 'applicant.preferredAge.maximum', selector: '#ageRangeMaximum', type: 'number' },
  { path: 'applicant.occupation', selector: '#ch3-1 input[placeholder="e.g. Product Manager"]' },
  { path: 'applicant.employer', selector: '#ch3-1 input[placeholder="e.g. Visteon"]' },
  { path: 'applicant.industry', selector: '#ch3-1 input[placeholder="e.g. Automotive tech"]' },
  { path: 'applicant.highestDegree', selector: '#ch3-1 input[placeholder="e.g. Bachelor\'s"]' },
  { path: 'applicant.institution', selector: '#ch3-1 input[placeholder="e.g. VIT Chennai"]' },
  { path: 'applicant.height.feet', selector: '#heightFtRow input:nth-child(1)', type: 'number' },
  { path: 'applicant.height.inches', selector: '#heightFtRow input:nth-child(2)', type: 'number' },
  { path: 'applicant.height.centimeters', selector: '#heightCmInput', type: 'number' },
  { path: 'applicant.linkedinUrl', selector: '#linkedinInput' },
  { path: 'applicant.livingSituation', selector: '#ch4-1 .pill-group', index: 0, type: 'choice' },
  { path: 'applicant.livingSituationOther', selector: '#livingOtherInput' },
  { path: 'applicant.willingToRelocate', selector: '#ch4-1 .pill-group', index: 1, type: 'choice' },
  { path: 'applicant.hasChildren', selector: '#ch4-2 .pill-group', index: 0, type: 'choice' },
  { path: 'applicant.wantsChildren', selector: '#ch4-2 .pill-group', index: 1, type: 'choice' },
  { path: 'applicant.childrenNonNegotiable', selector: '#ch4-2 .pill-group', index: 2, type: 'choice' },
  { path: 'applicant.maritalStatus', selector: '#ch5-1 .pill-group', index: 0, type: 'choice' },
  { path: 'applicant.faithBackground', selector: '#ch5-1 select' },
  { path: 'applicant.diet', selector: '#ch5-2 .pill-group', index: 0, type: 'choice' },
  { path: 'applicant.drinking', selector: '#ch5-2 .pill-group', index: 1, type: 'choice' },
  { path: 'applicant.smoking', selector: '#ch5-2 .pill-group', index: 2, type: 'choice' },
  { path: 'applicant.nonNegotiables', selector: '#boundariesText' },
  { path: 'applicant.partnershipRole', selector: '#ch7-1 textarea' },
  { path: 'applicant.friendsDescribe', selector: '#ch7-2 textarea' },
  { path: 'applicant.friendsTease', selector: '#ch7-3 textarea' },
  { path: 'applicant.ordinaryEvening', selector: '#ch7-4 textarea' },
  { path: 'applicant.relationshipLearning', selector: '#ch7-5 textarea' },
  { path: 'applicant.anythingElse', selector: '#ch7-6 textarea' },
])

export const applicationFieldPaths = Object.freeze(fieldBindings.map(({ path }) => path))
